# Generated by Django 5.0.3 on 2024-03-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_store_custo_first_n_a7e990_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
